services:
  main-db:
    image: 'postgres'
    container_name: 'm-database-container'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=134679002
      - POSTGRES_DB=session
    ports:
      - "2347:5432"

  test-db:
    image: 'postgres'
    container_name: 't-database-container'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=134679002
      - POSTGRES_DB=session
    ports:
      - "2348:5432"